---

- name: Removing Cloud-Init package...
  yum: name=cloud-init state=absent

- name: Removing vagrant user...
  user:
   name: vagrant
   state: absent
  
- name: Removing vagrant group...
  user:
   name: vagrant
   state: absent

- name: Removing vagrant directory...
  file:
   path: /vagrant/
   state: absent
