---

- name: Copying libwbxml libraries...
  copy:
   src: roles/sogo/templates/rpm/{{ item }}
   dest: /tmp/{{ item }}
   mode: 0644
  with_items:
   - libwbxml-0.11.6-1.el7.centos.x86_64.rpm
   - libwbxml-devel-0.11.6-1.el7.centos.x86_64.rpm
  register: result
  ignore_errors: true

- name: Installing libwbxml libraries...
  command: rpm -ivh /tmp/{{ item }}
  with_items:
   - libwbxml-0.11.6-1.el7.centos.x86_64.rpm
   - libwbxml-devel-0.11.6-1.el7.centos.x86_64.rpm
  ignore_errors: true

