---

- name: Creating SOGo group...
  group:
    name: sogo
    state: present

- name: Create SOGo user...
  user:
   name: sogo
   groups:
    - sogo
   state: present
   shell: /sbin/nologin
   createhome: yes
   home: /var/lib/sogo

- include: copy_sogo_src.yml
- include: install_sogo_deps.yml
- include: install_libwbxml.yml
- include: compile_sogo.yml
- include: copy_sogo_configs.yml

